### ISSUE TITLE
Unable to create tensorbuffer output

### ISSUE THREAD

**Issue by PatroxGaurab** [v-hogood/Xamarin.TensorFlow.Lite.Support#1]
`            TensorBuffer outputs = TensorBuffer.CreateFixedSize(new float[] { 1, 2048 }, DataType.Float32);
`
Error: Tensorbuffer does not contain a definition of CreateFixedSize

**Comment by PatroxGaurab** [comment]
Another issue is there ->
So basically there is no constructor for TensorImage that takes the DataType as parameter.
Java.Lang.IllegalArgumentException: 'DataType error: cannot resolve DataType of org.tensorflow.lite.support.image.TensorImage

**Comment by v-hogood** [comment]
Right you are!  Should be fixed; let me know if not.
