### ISSUE TITLE
dotnet MAUI support?

### ISSUE THREAD

**Issue by Th3L0x** [v-hogood/Xamarin.TensorFlow.Lite.Support#2]
Hi, when I try to install TensorFlowLiteTaskVision.iOS nuget package I receive this error message: 
"Error NU1202	Package TensorFlowLiteTaskVision.iOS 0.4.3 is not compatible with net8.0-ios17.2 (.NETCoreApp,Version=v8.0) / android-x86. Package TensorFlowLiteTaskVision.iOS 0.4.3 supports: xamarinios10 (Xamarin.iOS,Version=v1.0)	ProjectAgiturMaui	C:\Users\User\source\repos\MAUIApp\MAUIApp\MAUIApp.csproj"

The TensorFlowLite.iOS and TensorFlowLiteSelectTfOps.iOS installed without a problem.

Also the android versions installs (and run) without any problem.

I saw that the TensorFlowLite.iOS and TensorFlowLiteSelectTfOps.iOS has these dependecies: net7.0-ios-16.1
but the TensorFlowLiteTaskVision.iOS has this dependecy: Xamarin.iOS,Version=1.0

Do you plan to upgrade this project to dotnet MAUI, since Xamarin support will end on may 1.

My setup: 
net8.0-ios, min iOS version 14.2
net8.0-android  min Android version 21.0

**Comment by Th3L0x** [comment]
I managed to install the package but only with this version :
"TensorFlowLiteTaskVision.iOS" Version="0.4.3.1"
(In nuget package manager only the 0.4.3 version available)
Also I  had to increase the SupportediOSVersion to 17.2

But when I want to use the code from the ImageClassification example it does not see any classes in the TensorFlowLiteTaskVision namespace.

It only has three enums: 
TensorFlowLiteTaskVision.CoreMLDelegateEnabledDevices, 
TensorFlowLiteTaskVision.TFLOutputType, 
TensorFlowLiteTaskVision.TFLSupportErrorCode

(I downloaded the sample project too and this problem occurs there too)

**Comment by v-hogood** [comment]
Hi, I just published the 0.4.3.1 versions to nuget.org let me know if those work thanks.
Also Tensor Flow Lite tasks seem to be moving to Media Pipe so you might want to look at that:
https://developers.google.com/mediapipe/solutions/tasks

**Comment by Th3L0x** [comment]
Thank you, I installed the latest version, but unfourtunatly it still only sees the 3 enum (CoreMLDelegateEnabledDevices, TFLOutputType, TFLSupportErrorCode)

**Comment by v-hogood** [comment]
I just tried the 0.4.3.1 TensorFlowLiteTask packages with TensorFlowLiteExamples.iOS and they all worked.
Could you clear your nuget cache (e.g. rm -rf ~/.nuget/packages/tensorflowlitetask*) and try again?
Otherwise it might be a net8.0-ios17.2 compatibility issue.

**Comment by Th3L0x** [comment]
Thank you, it's working!

**Comment by v-hogood** [comment]
Great thanks for trying it!
