### ISSUE TITLE
iOS bug, maybe update to dotnet 9.0? 

### ISSUE THREAD

**Issue by Th3L0x** [v-hogood/Xamarin.TensorFlow.Lite.Support#3]
Message =
"Could not find the type 'ObjCRuntime.Registrar' in the assembly 'TensorFlowLite'."
Source =
"Microsoft.iOS"
StackTrace =
" at ObjCRuntime.RegistrarHelper.GetMapEntry(String assemblyName) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/RegistrarHelper.cs:line 105\n at ObjCRuntime.RegistrarHelper.GetMapEntry(Assembly assembly) in /Users/builder/azdo/_work/1/s/xam…"

**Comment by v-hogood** [comment]
See https://blog.ostebaronen.dk/2024/11/dotnet9-gotchas.html
